#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

1 or 0 @ 0  # Python >= 3.5 is required

import collections
import sys

class Dict(collections.OrderedDict):
    def __missing__(self, key):
        return []

def main():
    data = Dict()
    for line in sys.stdin:
        line = line.rstrip()
        [host, key] = line.split(' ', 1)
        data[key] += [host]
    for key, hosts in data.items():
        print(','.join(hosts), key)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
